[lib]
crate-type = ["cdylib"]

[package]
name = "luke_vault"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.0.0"
getrandom = { version = "0.2", features = ["js"] } # This tells `getrandom` to use a JavaScript-compatible implementation that works with SBF.